.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "OMI\-FACTORY" "1" "October 2014" "" ""
.
.SH "NAME"
\fBomi\-factory\fR \- build TurnKey Linux appliances
.
.SH "SYNOPSIS"
\fBomi\-factory\fR [\fIcommon\-options\fR] \fIcommand\fR [\fIcommand\-options\fR]
.
.SH "DESCRIPTION"
\fBomi\-factory\fR provides a set of commands to create OMIs for TurnKey Linux appliances\.
.
.P
It should be run as root, from a TurnKey Linux development environment such as \fBtkldev\fR\.
.
.P
The following commands are provided:
.
.TP
\fBcreate\-volume\fR
Create and attach a new volume
.
.TP
\fBdestroy\-volume\fR
Destroy an existing volume
.
.TP
\fBtkl\-build\fR
Build a TKL appliance
.
.TP
\fBinstall\-iso\fR
Install a system from an ISO file to a device
.
.TP
\fBtkl\-clean\fR
Clean TKL build dirs
.
.TP
\fBcreate\-image\fR
Create an AMI from an existing volume
.
.SH "COMMON OPTIONS"
.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Be more verbose: print debug output\.
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show the help message and exit\.
.
.SH "CREATE\-VOLUME COMMAND"
\fBomi\-factory create\-volume\fR [\fIoptions\fR] \fIvolume_size\fR
.
.P
Creates a new volume and attaches it to the instance\. On success it will print the \fBDEVICE\fR and \fBVOLUME_ID\fR shell variables to \fBstdout\fR\.
.
.TP
\fIvolume_size\fR
Size of the volume in GiBs\.
.
.P
Options:
.
.TP
\fB\-\-instance\-id\fR \fIinstance_id\fR
The id of the instance the volume should be attached to\. Defaults to the local instance\.
.
.TP
\fB\-\-volume\-location\fR \fIlocation\fR
Which location to use for the volume\. Defaults to \fIeu\-west\-1a\fR\.
.
.TP
\fB\-\-region\fR \fIregion\fR
The EC2 region to use\. Defaults to \fIeu\-west\-1\fR\.
.
.TP
\fB\-\-tags\fR \fIjson\fR
Tags to assign to the volume\. The value of this option must be a dictionary represented as a JSON string, for example: \fB\-\-tags "{ \'user\': \'me\' }"\fR\.
.
.SH "DESTROY\-VOLUME COMMAND"
`omi\-factory destroy\-volume [\fIoptions\fR] \fIvolume\-id\fR
.
.P
Destroys a volume\.
.
.TP
\fIvolume\-id\fR
Which volume to destroy\.
.
.P
Options:
.
.TP
\fB\-\-region\fR \fIregion\fR
The EC2 region to use\. Defaults to \fIeu\-west\-1\fR\.
.
.SH "TKL\-BUILD COMMAND"
\fBomi\-factory tkl\-build\fR [\fIoptions\fR] \fIapp\fR
.
.P
Builds a Turn Key Linux appliance and installs it on a device\.
.
.TP
\fIapp\fR
The name of the TurnKey Linux appliance to build\.
.
.P
Mandatory option:
.
.TP
\fB\-d\fR \fIdevice\fR, \fB\-\-device\fR \fIdevice\fR
The block device onto which the appliance will be copied\.
.
.P
Directory options:
.
.TP
\fB\-p\fR \fIdirectory\fR, \fB\-\-patch\-dir\fR \fIdirectory\fR
The directory holding the patches used by tklpatch(1) to modify the appliance root filesystem\. The default is \fI/usr/local/share/tklpatch\fR\.
.
.TP
\fB\-f\fR \fIdirectory\fR, \fB\-\-fab\-dir\fR \fIdirectory\fR
The TurnKey factory directory\. The default is \fI/turnkey/fab\fR\.
.
.TP
\fB\-m\fR \fIdirectory\fR, \fB\-\-mount\-point\fR \fIdirectory\fR
The temporary mount point used to mount the block device\. The default is \fI/mnt\fR\.
.
.TP
\fB\-w\fR \fIdirectory\fR, \fB\-\-work\-dir\fR \fIdirectory\fR
The directory used to extract the root filesystem and apply patches with tklpatch(1)\. The default is \fI/tmp\fR\.
.
.P
Miscellaneous options:
.
.TP
\fB\-g\fR \fIurl\fR, \fB\-\-turnkey\-apps\-git\fR \fIurl\fR
The URL of the github account hosting each TurnKey Linux appliance\. The default is \fIhttps://github\.com/turnkeylinux\-apps\fR\.
.
.TP
\fB\-t\fR \fIpatch\fR, \fB\-\-turnkey\-apps\-git\fR \fIpatch\fR
Add a patch to the list of patches applied by tklpatch(1)\. The patch must be copied to the patch directory beforehand, see the \fB\-\-patch\-dir\fR option\. The default patch list is: \fIheadless\fR, \fIoutscale\fR\.
.
.SH "INSTALL\-ISO COMMAND"
\fBomi\-factory install\-iso\fR [\fIoptions\fR] \fIiso\-file\fR
.
.P
Installs a system from an ISO file to a device\.
.
.P
Unless you are doing things manually, you do not need this command: it is called by \fBtkl\-build\fR\.
.
.TP
\fIiso\-file\fR
Path to the ISO file to install\.
.
.P
Options:
.
.TP
\fB\-d\fR \fIdevice\fR, \fB\-\-device\fR \fIdevice\fR
The block device onto which the ISO will be copied\.
.
.TP
\fB\-p\fR \fIdirectory\fR, \fB\-\-patch\-dir\fR \fIdirectory\fR
The directory holding the patches used by tklpatch(1) to modify the appliance root filesystem\. The default is \fI/usr/local/share/tklpatch\fR\.
.
.TP
\fB\-t\fR \fIpatch\fR, \fB\-\-turnkey\-apps\-git\fR \fIpatch\fR
Add a patch to the list of patches applied by tklpatch(1)\. The patch must be copied to the patch directory beforehand, see the \fB\-\-patch\-dir\fR option\. The default patch list is: \fIheadless\fR, \fIoutscale\fR\.
.
.SH "TKL\-CLEAN COMMAND"
\fBomi\-factory tkl\-clean\fR [\fIoptions\fR] \fIapp\fR
.
.P
Cleans Turn Key Linux build dirs\.
.
.TP
\fIapp\fR
The name of the TurnKey Linux appliance to build\.
.
.P
Options:
.
.TP
\fB\-f\fR \fIdirectory\fR, \fB\-\-fab\-dir\fR \fIdirectory\fR
The TurnKey factory directory\. The default is \fI/turnkey/fab\fR\.
.
.SH "CREATE\-IMAGE COMMAND"
\fBomi\-factory create\-image\fR [\fIoptions\fR] \fIimage\-name\fR
.
.P
Creates an OMI from an existing volume\.
.
.TP
\fIimage\-name\fR
The name of the image to create\. This will be set as the \fBname\fR tag of the image\.
.
.P
Mandatory option:
.
.TP
\fB\-\-volume\-id\fR \fIvolume\fR
The id of the volume to create the image from\.
.
.P
Other options:
.
.TP
\fB\-\-image\-description\fR \fIdescription\fR
Some text describing the image\. Defaults to \fINone\fR\.
.
.TP
\fB\-\-image\-arch\fR \fIarch\fR
The machine architecture of the image\. Defaults to \fIx86_64\fR\.
.
.TP
\fB\-\-region\fR \fIregion\fR
The EC2 region to use\. Defaults to \fIeu\-west\-1\fR\.
.
.TP
\fB\-\-tags\fR \fIjson\fR
Tags to assign to the volume\. The value of this option must be a dictionary represented as a JSON string, for example: \fB\-\-tags "{ \'user\': \'me\' }"\fR\.
.
.SH "SEE ALSO"
tklpatch(1)
